openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API documentation for authentication endpoints

paths:
  /auth/login:
    post:
      summary: User login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        200:
          description: Login successful
        400:
          description: Bad request
        401:
          description: Unauthorized

  /auth/forgot-password:
    post:
      summary: Forgot password
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        200:
          description: Reset password link sent
        400:
          description: Bad request

  /auth/reset-password/{token}:
    post:
      summary: Reset password
      tags:
        - Authentication
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newPassword:
                  type: string
              required:
                - newPassword
      responses:
        200:
          description: Password reset successfully
        400:
          description: Bad request
        401:
          description: Unauthorized

  /auth/update-password:
    post:
      summary: Update password
      tags:
        - Authentication
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                newPassword:
                  type: string
              required:
                - currentPassword
                - newPassword
      responses:
        200:
          description: Password updated successfully
        400:
          description: Bad request
        401:
          description: Unauthorized

  /auth/verify/{token}:
    get:
      summary: Verify account
      tags:
        - Authentication
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Account verified successfully
        400:
          description: Bad request
        500:
          description: Internal server error