openapi: 3.0.0
info:
  title: Permissions API
  version: 1.0.0
  description: API documentation for managing permissions in Chafetz E-commerce.

paths:
  /permissions:
    post:
      summary: Create a new permission
      tags:
        - Permissions
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "manage_users"
      responses:
        '201':
          description: Permission created successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

    get:
      summary: Get all permissions
      tags:
        - Permissions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of permissions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
        '401':
          description: Unauthorized

  /permissions/{id}:
    put:
      summary: Update a permission by ID
      tags:
        - Permissions
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the permission to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "manage_users"
      responses:
        '200':
          description: Permission updated successfully
        '404':
          description: Permission not found ```yaml
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

    delete:
      summary: Delete a permission by ID
      tags:
        - Permissions
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the permission to delete
          schema:
            type: string
      responses:
        '200':
          description: Permission deleted successfully
        '404':
          description: Permission not found
        '401':
          description: Unauthorized
        '403':
          description: Forbidden