openapi: 3.0.0
info:
  title: Roles API
  version: 1.0.0
  description: API documentation for managing roles in Chafetz E-commerce.


paths:
  /roles:
    post:
      summary: Create a new role
      tags:
        - Roles
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "admin"
                displayName:
                  type: string
                  example: "Administrator"
      responses:
        '201':
          description: Role created successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

    get:
      summary: Get all roles
      tags:
        - Roles
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of roles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    displayName:
                      type: string
        '401':
          description: Unauthorized

  /roles/{id}:
    put:
      summary: Update a role by ID
      tags:
        - Roles
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the role to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "admin"
                displayName:
                  type: string
                  example: "Administrator"
      responses:
        '200':
          description: Role updated successfully
        '404':
          description: Role not found
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

    delete:
      summary: Delete a role by ID
      tags:
        - Roles
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the role to delete
          schema:
            type: string
      responses:
        '200':
          description: Role deleted successfully
        '404':
          description: Role not found
        '401':
          description: Unauthorized
        '403':
          description: Forbidden